# SPDX-FileCopyrightText: (C) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0
op_data_type_spec:
  global_type: int8
  override:
    dropout: int32

op_removal_spec:
  - Dropout
  - Identity
  - Constant

op_fusion_spec:
  - [Add, LayerNormalization, Matmul, Add, Matmul, Add, Gelu]
  - [Add, LayerNormalization, Matmul, Add, Split]
  - [Add, LayerNormalization, Matmul]
  - [Add, LayerNormalization]
  - [Reshape, Transpose, Transpose]
  - [Reshape, Transpose]
  - [Transpose, Transpose]
  - [Matmul, Add, Matmul, Add, Gelu]
  - [Matmul, Matmul]
  - [Matmul, Mul, Softmax]
  - [Matmul, Mul]
  - [Matmul, Add, Split]
  - [Matmul, Add, Gelu]
  - [Matmul, Add]
  - [Matmul, Gelu, Add]
  - [Matmul, Transpose, Reshape]
  - [Conv, Relu]
  - [Conv, BatchNormalization, Add, Relu, AveragePool, Reshape]
  - [Conv, BatchNormalization, Add, Relu]
  - [Conv, BatchNormalization, Relu, MaxPool]
  - [Conv, BatchNormalization, Relu]
  - [Conv, BatchNormalization, LeakyRelu]
  - [Conv, BatchNormalization, Sigmoid, Mul]
  - [Conv, BatchNormalization, Mul]
  - [Conv, BatchNormalization]
  # SDXL UNet specific fusion patterns
  - [Conv, GroupNorm, SiLU, Conv, GroupNorm, SiLU, Add]  # ResNet block
  - [GroupNorm, SiLU, Conv]  # ResNet sub-block
  - [LayerNorm, Linear, Linear, Linear, Softmax, Linear]  # Cross-attention
  - [LayerNorm, Linear, Gelu, Linear, Add]  # Feed-forward network
  - [Linear, Add, LayerNorm]  # Attention output projection
  - [Reshape, Permute, Matmul, Softmax, Matmul, Permute, Reshape]  # Full attention pattern (Permute variant)
  - [Reshape, Transpose, Matmul, Softmax, Matmul, Transpose, Reshape]  # Full attention pattern (Transpose variant)

op_rsrc_spec:
  compute:
    matrix: [Matmul, Conv, Conv2d]
    vector: [Gather, Reshape, Permute, Transpose, Gelu, Relu, LeakyRelu, Resize, Sigmoid, Slice,
             Flatten, ReduceMax, ArgMax, Cast, NonMaxSuppression, Add, Sub, Mul, Div,
             Dropout, Split, Softmax, LayerNormalization, GroupNormalization, Identity, Constant, Where,
             Pow, Tanh, MaxPool, BatchNormalization, Concat, Unsqueeze, Squeeze, Trilu,
             AveragePool, Tile, VoxelPooling, GroupNorm, SiLU, Linear, Sin, Cos, Exp,
             Arange, Meshgrid, Chunk, Pad, Triu, Var, Mean, Sqrt, Upsample
            ]
